In [2]:
import pandas as pd

Dataset loading

In [7]:
data_path = r"C:\Users\erica\Documents\Mestrado\Projetos\Ames_Housing_Project\data\raw\AmesHousing.csv"
df = pd.read_csv(data_path, index_col = "Order")
df.head()

,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
Order,,,,,,,,,,,,,,,,,,,,,
1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [8]:
df.columns

Index(['PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street',
       'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config',
       'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type',
       'House Style', 'Overall Qual', 'Overall Cond', 'Year Built',
       'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st',
       'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual',
       'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure',
       'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2',
       'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air',
       'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF',
       'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath',
       'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual',
       'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu',
       'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars',
       'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive',
       'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch',
       'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature',
       'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition',
       'SalePrice'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 1 to 2930
Data columns (total 81 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PID              2930 non-null   int64
 1   MS SubClass      2930 non-null   int64
 2   MS Zoning        2930 non-null   str
 3   Lot Frontage     2440 non-null   float64
 4   Lot Area         2930 non-null   int64
 5   Street           2930 non-null   str
 6   Alley            198 non-null    str
 7   Lot Shape        2930 non-null   str
 8   Land Contour     2930 non-null   str
 9   Utilities        2930 non-null   str
 10  Lot Config       2930 non-null   str
 11  Land Slope       2930 non-null   str
 12  Neighborhood     2930 non-null   str
 13  Condition 1      2930 non-null   str
 14  Condition 2      2930 non-null   str
 15  Bldg Type        2930 non-null   str
 16  House Style      2930 non-null   str
 17  Overall Qual     2930 non-null   int64
 18  Overall Cond     2930 non-null   int64
 19  Year Built       2930 non-null   int64
 20  Year Remod/Add   2930 non-null   int64
 21  Roof Style       2930 non-null   str
 22  Roof Matl        2930 non-null   str
 23  Exterior 1st     2930 non-null   str
 24  Exterior 2nd     2930 non-null   str
 25  Mas Vnr Type     1155 non-null   str
 26  Mas Vnr Area     2907 non-null   float64
 27  Exter Qual       2930 non-null   str
 28  Exter Cond       2930 non-null   str
 29  Foundation       2930 non-null   str
 30  Bsmt Qual        2850 non-null   str
 31  Bsmt Cond        2850 non-null   str
 32  Bsmt Exposure    2847 non-null   str
 33  BsmtFin Type 1   2850 non-null   str
 34  BsmtFin SF 1     2929 non-null   float64
 35  BsmtFin Type 2   2849 non-null   str
 36  BsmtFin SF 2     2929 non-null   float64
 37  Bsmt Unf SF      2929 non-null   float64
 38  Total Bsmt SF    2929 non-null   float64
 39  Heating          2930 non-null   str
 40  Heating QC       2930 non-null   str
 41  Central Air      2930 non-null   str
 42  Electrical       2929 non-null   str
 43  1st Flr SF       2930 non-null   int64
 44  2nd Flr SF       2930 non-null   int64
 45  Low Qual Fin SF  2930 non-null   int64
 46  Gr Liv Area      2930 non-null   int64
 47  Bsmt Full Bath   2928 non-null   float64
 48  Bsmt Half Bath   2928 non-null   float64
 49  Full Bath        2930 non-null   int64
 50  Half Bath        2930 non-null   int64
 51  Bedroom AbvGr    2930 non-null   int64
 52  Kitchen AbvGr    2930 non-null   int64
 53  Kitchen Qual     2930 non-null   str
 54  TotRms AbvGrd    2930 non-null   int64
 55  Functional       2930 non-null   str
 56  Fireplaces       2930 non-null   int64
 57  Fireplace Qu     1508 non-null   str
 58  Garage Type      2773 non-null   str
 59  Garage Yr Blt    2771 non-null   float64
 60  Garage Finish    2771 non-null   str
 61  Garage Cars      2929 non-null   float64
 62  Garage Area      2929 non-null   float64
 63  Garage Qual      2771 non-null   str
 64  Garage Cond      2771 non-null   str
 65  Paved Drive      2930 non-null   str
 66  Wood Deck SF     2930 non-null   int64
 67  Open Porch SF    2930 non-null   int64
 68  Enclosed Porch   2930 non-null   int64
 69  3Ssn Porch       2930 non-null   int64
 70  Screen Porch     2930 non-null   int64
 71  Pool Area        2930 non-null   int64
 72  Pool QC          13 non-null     str
 73  Fence            572 non-null    str
 74  Misc Feature     106 non-null    str
 75  Misc Val         2930 non-null   int64
 76  Mo Sold          2930 non-null   int64
 77  Yr Sold          2930 non-null   int64
 78  Sale Type        2930 non-null   str
 79  Sale Condition   2930 non-null   str
 80  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(27), str(43)
memory usage: 1.8 MB

In [19]:
for col in df.columns:
    print(f"{col} -------- {df[col].dtype}")

PID -------- int64
MS SubClass -------- int64
MS Zoning -------- str
Lot Frontage -------- float64
Lot Area -------- int64
Street -------- str
Alley -------- str
Lot Shape -------- str
Land Contour -------- str
Utilities -------- str
Lot Config -------- str
Land Slope -------- str
Neighborhood -------- str
Condition 1 -------- str
Condition 2 -------- str
Bldg Type -------- str
House Style -------- str
Overall Qual -------- int64
Overall Cond -------- int64
Year Built -------- int64
Year Remod/Add -------- int64
Roof Style -------- str
Roof Matl -------- str
Exterior 1st -------- str
Exterior 2nd -------- str
Mas Vnr Type -------- str
Mas Vnr Area -------- float64
Exter Qual -------- str
Exter Cond -------- str
Foundation -------- str
Bsmt Qual -------- str
Bsmt Cond -------- str
Bsmt Exposure -------- str
BsmtFin Type 1 -------- str
BsmtFin SF 1 -------- float64
BsmtFin Type 2 -------- str
BsmtFin SF 2 -------- float64
Bsmt Unf SF -------- float64
Total Bsmt SF -------- float64
Heating -------- str
Heating QC -------- str
Central Air -------- str
Electrical -------- str
1st Flr SF -------- int64
2nd Flr SF -------- int64
Low Qual Fin SF -------- int64
Gr Liv Area -------- int64
Bsmt Full Bath -------- float64
Bsmt Half Bath -------- float64
Full Bath -------- int64
Half Bath -------- int64
Bedroom AbvGr -------- int64
Kitchen AbvGr -------- int64
Kitchen Qual -------- str
TotRms AbvGrd -------- int64
Functional -------- str
Fireplaces -------- int64
Fireplace Qu -------- str
Garage Type -------- str
Garage Yr Blt -------- float64
Garage Finish -------- str
Garage Cars -------- float64
Garage Area -------- float64
Garage Qual -------- str
Garage Cond -------- str
Paved Drive -------- str
Wood Deck SF -------- int64
Open Porch SF -------- int64
Enclosed Porch -------- int64
3Ssn Porch -------- int64
Screen Porch -------- int64
Pool Area -------- int64
Pool QC -------- str
Fence -------- str
Misc Feature -------- str
Misc Val -------- int64
Mo Sold -------- int64
Yr Sold -------- int64
Sale Type -------- str
Sale Condition -------- str
SalePrice -------- int64

In [28]:
for col in df.columns:
    print(f"""------- {col} -------- 
          
          valores unicos: {df[col].unique()} 
          quantidade de valores unicos: {df[col].nunique()}""")

------- PID --------

          valores unicos: [526301100 526350040 526351010 ... 923400125 924100070 924151050]
          quantidade de valores unicos: 2930
------- MS SubClass --------

          valores unicos: [ 20  60 120  50  85 160  80  30  90 190  45  70  75  40 180 150]
          quantidade de valores unicos: 16
------- MS Zoning --------

          valores unicos: <StringArray>
['RL', 'RH', 'FV', 'RM', 'C (all)', 'I (all)', 'A (agr)']
Length: 7, dtype: str
          quantidade de valores unicos: 7
------- Lot Frontage --------

          valores unicos: [141.  80.  81.  93.  74.  78.  41.  43.  39.  60.  75.  nan  63.  85.
  47. 152.  88. 140. 105.  65.  70.  26.  21.  53.  24. 102.  98.  83.
  94.  95.  90.  79. 100.  44. 110.  61.  36.  67. 108.  59.  92.  58.
  56.  73.  72.  84.  76.  50.  55.  68. 107.  25.  30.  57.  40.  77.
 120. 137.  87. 119.  64.  96.  71.  69.  52.  51.  54.  86. 124.  82.
  38.  48.  89.  66.  45.  35. 129.  31.  42.  28.  99. 104.  97. 103.
  34. 117. 149. 122.  62. 174. 106. 112.  32. 115. 128.  91.  33. 121.
 144. 130. 109. 150. 113. 125. 101.  46. 114. 135. 136.  37.  22. 313.
  49. 123. 160. 195. 118. 134. 182. 116. 138. 155. 126. 200. 168. 111.
 131. 153. 133.]
          quantidade de valores unicos: 128
------- Lot Area --------

          valores unicos: [31770 11622 14267 ...  7937  8885 10441]
          quantidade de valores unicos: 1960
------- Street --------

          valores unicos: <StringArray>
['Pave', 'Grvl']
Length: 2, dtype: str
          quantidade de valores unicos: 2
------- Alley --------

          valores unicos: <StringArray>
[nan, 'Pave', 'Grvl']
Length: 3, dtype: str
          quantidade de valores unicos: 2
------- Lot Shape --------

          valores unicos: <StringArray>
['IR1', 'Reg', 'IR2', 'IR3']
Length: 4, dtype: str
          quantidade de valores unicos: 4
------- Land Contour --------

          valores unicos: <StringArray>
['Lvl', 'HLS', 'Bnk', 'Low']
Length: 4, dtype: str
          quantidade de valores unicos: 4
------- Utilities --------

          valores unicos: <StringArray>
['AllPub', 'NoSewr', 'NoSeWa']
Length: 3, dtype: str
          quantidade de valores unicos: 3
------- Lot Config --------

          valores unicos: <StringArray>
['Corner', 'Inside', 'CulDSac', 'FR2', 'FR3']
Length: 5, dtype: str
          quantidade de valores unicos: 5
------- Land Slope --------

          valores unicos: <StringArray>
['Gtl', 'Mod', 'Sev']
Length: 3, dtype: str
          quantidade de valores unicos: 3
------- Neighborhood --------

          valores unicos: <StringArray>
[  'NAmes', 'Gilbert', 'StoneBr',  'NWAmes', 'Somerst',  'BrDale', 'NPkVill',
 'NridgHt', 'Blmngtn', 'NoRidge', 'SawyerW',  'Sawyer',  'Greens', 'BrkSide',
 'OldTown',  'IDOTRR', 'ClearCr',   'SWISU', 'Edwards', 'CollgCr', 'Crawfor',
 'Blueste', 'Mitchel',  'Timber', 'MeadowV', 'Veenker', 'GrnHill', 'Landmrk']
Length: 28, dtype: str
          quantidade de valores unicos: 28
------- Condition 1 --------

          valores unicos: <StringArray>
['Norm', 'Feedr', 'PosN', 'RRNe', 'RRAe', 'Artery', 'PosA', 'RRAn', 'RRNn']
Length: 9, dtype: str
          quantidade de valores unicos: 9
------- Condition 2 --------

          valores unicos: <StringArray>
['Norm', 'Feedr', 'PosA', 'PosN', 'Artery', 'RRNn', 'RRAe', 'RRAn']
Length: 8, dtype: str
          quantidade de valores unicos: 8
------- Bldg Type --------

          valores unicos: <StringArray>
['1Fam', 'TwnhsE', 'Twnhs', 'Duplex', '2fmCon']
Length: 5, dtype: str
          quantidade de valores unicos: 5
------- House Style --------

          valores unicos: <StringArray>
['1Story', '2Story', '1.5Fin', 'SFoyer', 'SLvl', '2.5Unf', '1.5Unf', '2.5Fin']
Length: 8, dtype: str
          quantidade de valores unicos: 8
------- Overall Qual --------

          valores unicos: [ 6  5  7  8  9  4  3  2 10  1]
          quantidade de valores unicos: 10
------- Overall Cond --------

          valores unicos: [5 6 7 2 8 4 9 3 1]
          quantidade de valores unicos: 9
------- Year Built --------

          valores unicos: [1960 1961 1958 1968 1997 1998 2001 1992 1995 1999 1993 1990 1985 2003
 1988 2010 1951 1978 1977 1974 2000 1970 1971 1975 2009 2007 2005 2004
 2002 2006 1996 1994 2008 1980 1979 1984 1920 1965 1967 1963 1962 1976
 1972 1966 1959 1964 1950 1952 1949 1940 1954 1955 1957 1956 1953 1948
 1900 1910 1927 1915 1945 1929 1938 1923 1928 1890 1885 1922 1925 1939
 1942 1936 1930 1921 1912 1917 1907 1875 1969 1947 1946 1987 1941 1924
 1914 1931 1919 1989 1896 1973 1991 1981 1986 1916 1926 1935 1892 1898
 1880 1882 1937 1902 1934 1982 1983 1932 1918 1904 1905 1872 1893 1906
 1908 1911 1895 1879 1901 1913]
          quantidade de valores unicos: 118
------- Year Remod/Add --------

          valores unicos: [1960 1961 1958 1968 1998 2001 1992 1996 1999 1994 2007 1990 1985 2003
 2005 2010 1951 1988 1977 1974 2000 1970 2008 1971 1975 1978 2006 2004
 2002 1995 2009 1980 1979 1984 1981 1950 1967 1963 1993 1966 1959 1964
 1954 1972 1989 1957 1956 1952 1955 1962 1997 1965 1969 1987 1976 1991
 1973 1986 1983 1953 1982]
          quantidade de valores unicos: 61
------- Roof Style --------

          valores unicos: <StringArray>
['Hip', 'Gable', 'Mansard', 'Gambrel', 'Shed', 'Flat']
Length: 6, dtype: str
          quantidade de valores unicos: 6
------- Roof Matl --------

          valores unicos: <StringArray>
['CompShg', 'WdShake', 'Tar&Grv', 'WdShngl', 'Membran', 'ClyTile',    'Roll',
   'Metal']
Length: 8, dtype: str
          quantidade de valores unicos: 8
------- Exterior 1st --------

          valores unicos: <StringArray>
['BrkFace', 'VinylSd', 'Wd Sdng', 'CemntBd', 'HdBoard', 'Plywood', 'MetalSd',
 'AsbShng', 'WdShing',  'Stucco', 'AsphShn', 'BrkComm',  'CBlock', 'PreCast',
   'Stone', 'ImStucc']
Length: 16, dtype: str
          quantidade de valores unicos: 16
------- Exterior 2nd --------

          valores unicos: <StringArray>
['Plywood', 'VinylSd', 'Wd Sdng', 'BrkFace', 'CmentBd', 'HdBoard', 'Wd Shng',
 'MetalSd', 'ImStucc', 'Brk Cmn', 'AsbShng',  'Stucco', 'AsphShn',  'CBlock',
   'Stone', 'PreCast',   'Other']
Length: 17, dtype: str
          quantidade de valores unicos: 17
------- Mas Vnr Type --------

          valores unicos: <StringArray>
['Stone', nan, 'BrkFace', 'BrkCmn', 'CBlock']
Length: 5, dtype: str
          quantidade de valores unicos: 4
------- Mas Vnr Area --------

          valores unicos: [1.120e+02 0.000e+00 1.080e+02 2.000e+01 6.030e+02 3.500e+02 1.190e+02
 4.800e+02 8.100e+01 1.800e+02 5.040e+02 4.920e+02 3.810e+02 1.620e+02
 2.000e+02 4.500e+02 2.560e+02 2.260e+02 6.150e+02 2.400e+02 1.680e+02
 7.600e+02 1.280e+02 1.095e+03 2.320e+02 4.120e+02 1.780e+02 1.060e+02
 1.400e+01 1.600e+01       nan 1.650e+02 1.140e+02 3.380e+02 3.620e+02
 3.480e+02 3.000e+01 5.790e+02 3.600e+01 1.220e+02 1.300e+02 3.100e+01
 2.500e+02 1.200e+02 2.160e+02 4.320e+02 1.159e+03 2.890e+02 2.800e+01
 4.200e+01 1.720e+02 4.510e+02 2.680e+02 8.600e+01 1.560e+02 1.440e+02
 2.650e+02 3.400e+02 1.100e+02 1.640e+02 3.610e+02 2.870e+02 5.060e+02
 1.500e+02 2.200e+02 3.240e+02 9.100e+01 1.040e+02 3.000e+02 2.610e+02
 2.180e+02 3.510e+02 7.710e+02 2.940e+02 9.000e+01 7.200e+01 4.700e+01
 1.430e+02 3.280e+02 2.880e+02 9.600e+01 3.360e+02 1.770e+02 8.500e+01
 2.460e+02 2.400e+01 8.000e+01 1.160e+02 1.530e+02 3.200e+02 4.790e+02
 2.230e+02 4.420e+02 1.700e+02 1.690e+02 1.710e+02 1.090e+02 9.800e+01
 1.450e+02 2.030e+02 3.710e+02 4.300e+02 4.400e+01 1.860e+02 3.350e+02
 6.000e+01 8.400e+01 1.890e+02 4.400e+02 1.880e+02 3.200e+01 1.600e+02
 2.200e+01 4.000e+01 6.800e+01 4.500e+01 3.440e+02 7.480e+02 4.640e+02
 1.570e+02 2.780e+02 2.090e+02 1.260e+02 1.010e+02 2.290e+02 2.250e+02
 2.060e+02 1.610e+02 1.960e+02 1.740e+02 3.330e+02 7.600e+01 3.120e+02
 1.420e+02 4.250e+02 5.100e+02 2.300e+02 7.260e+02 8.600e+02 6.400e+02
 3.060e+02 1.540e+02 3.050e+02 4.200e+02 4.720e+02 4.240e+02 3.020e+02
 2.380e+02 2.840e+02 2.620e+02 2.850e+02 2.960e+02 4.180e+02 9.220e+02
 7.240e+02 3.830e+02 1.350e+02 1.760e+02 1.660e+02 7.300e+02 4.700e+02
 3.080e+02 5.000e+02 2.700e+02 1.630e+02 1.100e+01 2.100e+02 2.980e+02
 6.730e+02 7.310e+02 9.750e+02 9.210e+02 6.340e+02 2.860e+02 3.720e+02
 5.280e+02 1.940e+02 2.600e+02 1.980e+02 1.210e+02 1.000e+02 2.640e+02
 1.400e+02 1.320e+02 3.660e+02 1.410e+02 1.150e+02 2.800e+02 2.520e+02
 8.940e+02 5.130e+02 4.560e+02 5.710e+02 3.590e+02 2.830e+02 3.600e+02
 5.090e+02 7.000e+01 9.500e+01 2.170e+02 3.000e+00 2.470e+02 5.760e+02
 1.830e+02 3.990e+02 6.500e+02 6.570e+02 2.950e+02 3.680e+02 8.200e+01
 1.240e+02 4.440e+02 9.200e+01 8.900e+01 2.300e+01 5.400e+01 1.490e+02
 2.340e+02 1.370e+02 2.750e+02 2.420e+02 3.640e+02 3.520e+02 1.360e+02
 2.040e+02 5.730e+02 2.550e+02 7.400e+01 2.590e+02 8.800e+01 5.410e+02
 4.060e+02 3.100e+02 5.840e+02 2.900e+02 1.820e+02 7.500e+01 2.450e+02
 1.230e+02 1.020e+02 6.210e+02 6.600e+02 4.020e+02 1.580e+02 4.220e+02
 1.270e+02 6.040e+02 3.560e+02 6.500e+01 4.260e+02 2.720e+02 8.160e+02
 4.360e+02 5.540e+02 4.680e+02 6.800e+02 6.640e+02 2.920e+02 1.110e+03
 2.210e+02 7.660e+02 6.160e+02 7.140e+02 1.460e+02 3.180e+02 6.470e+02
 1.290e+03 4.730e+02 4.950e+02 4.660e+02 6.510e+02 4.480e+02 5.300e+01
 7.680e+02 3.800e+01 2.580e+02 3.040e+02 5.680e+02 1.790e+02 2.120e+02
 1.050e+03 5.640e+02 3.420e+02 1.480e+02 2.430e+02 4.910e+02 2.370e+02
 4.100e+02 1.510e+02 1.870e+02 3.870e+02 5.200e+01 1.250e+02 2.760e+02
 4.150e+02 3.900e+01 4.100e+01 2.990e+02 9.900e+01 1.900e+02 2.510e+02
 2.810e+02 2.270e+02 2.020e+02 3.960e+02 1.340e+02 1.920e+02 2.050e+02
 2.150e+02 1.130e+02 5.000e+01 2.660e+02 1.470e+02 2.220e+02 7.960e+02
 5.800e+01 6.320e+02 6.680e+02 2.280e+02 2.190e+02 6.740e+02 1.970e+02
 1.115e+03 1.380e+02 7.100e+02 9.450e+02 6.700e+01 5.490e+02 2.330e+02
 2.530e+02 2.630e+02 3.650e+02 5.670e+02 3.760e+02 3.780e+02 4.520e+02
 2.540e+02 3.150e+02 4.000e+02 3.750e+02 7.720e+02 2.480e+02 9.700e+02
 5.020e+02 3.880e+02 3.940e+02 2.350e+02 5.150e+02 7.050e+02 1.170e+03
 5.940e+02 3.090e+02 5.260e+02 7.540e+02 2.080e+02 4.280e+02 3.530e+02
 1.050e+02 5.700e+01 3.370e+02 1.129e+03 1.600e+03 6.000e+02 1.000e+00
 5.250e+02 6.600e+01 6.300e+01 5.600e+01 2.240e+02 8.700e+01 2.910e+02
 6.900e+01 2.790e+02 4.350e+02 3.230e+02 1.670e+02 5.100e+01 2.140e+02
 5.190e+02 4.380e+02 4.800e+01 1.224e+03 7.620e+02 4.230e+02 1.840e+02
 6.520e+02 4.810e+02 2.390e+02 2.740e+02 1.170e+02 8.860e+02 2.360e+02
 9.400e+01 2.440e+02 9.020e+02 4.340e+02 2.700e+01 6.620e+02 7.340e+02
 5.500e+02 1.031e+03 3.400e+01 5.140e+02 4.080e+02 3.800e+02 2.970e+02
 3.700e+02 3.850e+02 7.880e+02 5.620e+02 8.700e+02 5.180e+02 5.720e+02
 1.800e+01 3.220e+02 1.378e+03 8.770e+02 5.300e+02 3.970e+02 7.380e+02
 5.010e+02 3.910e+02 1.180e+02 4.600e+01 6.920e+02 3.320e+02 1.750e+02
 6.400e+01 5.220e+02 1.047e+03 3.790e+02 2.070e+02 9.700e+01 5.320e+02
 6.200e+01 1.990e+02 3.550e+02 4.590e+02 4.050e+02 3.270e+02 2.570e+02
 2.930e+02 6.530e+02 6.300e+02 3.820e+02 4.430e+02]
          quantidade de valores unicos: 445
------- Exter Qual --------

          valores unicos: <StringArray>
['TA', 'Gd', 'Ex', 'Fa']
Length: 4, dtype: str
          quantidade de valores unicos: 4
------- Exter Cond --------

          valores unicos: <StringArray>
['TA', 'Gd', 'Fa', 'Po', 'Ex']
Length: 5, dtype: str
          quantidade de valores unicos: 5
------- Foundation --------

          valores unicos: <StringArray>
['CBlock', 'PConc', 'Wood', 'BrkTil', 'Slab', 'Stone']
Length: 6, dtype: str
          quantidade de valores unicos: 6
------- Bsmt Qual --------

          valores unicos: <StringArray>
['TA', 'Gd', 'Ex', nan, 'Fa', 'Po']
Length: 6, dtype: str
          quantidade de valores unicos: 5
------- Bsmt Cond --------

          valores unicos: <StringArray>
['Gd', 'TA', nan, 'Po', 'Fa', 'Ex']
Length: 6, dtype: str
          quantidade de valores unicos: 5
------- Bsmt Exposure --------

          valores unicos: <StringArray>
['Gd', 'No', 'Mn', 'Av', nan]
Length: 5, dtype: str
          quantidade de valores unicos: 4
------- BsmtFin Type 1 --------

          valores unicos: <StringArray>
['BLQ', 'Rec', 'ALQ', 'GLQ', 'Unf', 'LwQ', nan]
Length: 7, dtype: str
          quantidade de valores unicos: 6
------- BsmtFin SF 1 --------

          valores unicos: [6.390e+02 4.680e+02 9.230e+02 1.065e+03 7.910e+02 6.020e+02 6.160e+02
 2.630e+02 1.180e+03 0.000e+00 9.350e+02 6.370e+02 3.680e+02 1.416e+03
 4.270e+02 1.445e+03 1.200e+02 7.900e+02 7.050e+02 8.850e+02 5.330e+02
 5.780e+02 7.340e+02 7.750e+02 8.040e+02 4.320e+02 1.051e+03 1.560e+02
 3.000e+02 3.600e+02 5.140e+02 3.110e+02 1.218e+03 1.646e+03 1.201e+03
 1.100e+02 2.800e+01 2.000e+00 2.188e+03 7.330e+02 1.373e+03 4.560e+02
 2.400e+01 1.600e+01 3.260e+02 6.250e+02 2.500e+02 9.190e+02 1.032e+03
 5.240e+02 8.160e+02 1.078e+03 2.220e+02 1.414e+03 6.560e+02 6.950e+02
 5.430e+02 6.230e+02 4.020e+02 3.380e+02 8.990e+02 5.530e+02 4.500e+02
 8.240e+02 6.590e+02 1.260e+02 6.740e+02 1.129e+03 1.298e+03 2.800e+02
 3.760e+02 3.780e+02 4.660e+02 6.040e+02 2.440e+02 4.840e+02 7.280e+02
 1.052e+03 8.330e+02 5.060e+02 1.137e+03 1.200e+03 6.870e+02 3.940e+02
 9.820e+02 3.290e+02 6.980e+02 5.690e+02 1.059e+03 1.010e+03 1.014e+03
 7.630e+02 1.500e+03 4.900e+01 6.700e+02 6.960e+02 3.540e+02 5.400e+02
 9.440e+02 4.430e+02 9.120e+02 2.470e+02 1.188e+03 8.560e+02 1.018e+03
 9.220e+02 1.000e+03 6.970e+02 9.360e+02 3.390e+02 6.480e+02 5.320e+02
 7.310e+02 3.200e+02 2.480e+02 1.056e+03 7.200e+01 4.810e+02 3.400e+02
 5.070e+02 2.340e+02 5.880e+02 7.170e+02 4.800e+01 5.790e+02 2.740e+02
 5.100e+02 7.800e+02 1.760e+02 6.860e+02 6.000e+02 2.830e+02 7.880e+02
 4.740e+02 1.880e+02 4.520e+02 2.640e+02 2.760e+02 4.480e+02 9.600e+02
 1.040e+02 7.660e+02 1.026e+03 7.300e+01 7.360e+02 7.040e+02 8.410e+02
 1.302e+03 8.420e+02 2.400e+02 3.710e+02 1.319e+03 2.670e+02 4.380e+02
 1.092e+03 4.420e+02 1.258e+03 9.640e+02 2.880e+02 1.080e+02 7.390e+02
 1.920e+02 9.540e+02 3.600e+01 1.346e+03 1.433e+03 8.600e+02 7.500e+02
 7.470e+02 1.470e+03 5.040e+02 8.700e+02 3.530e+02 5.050e+02 1.980e+02
 1.820e+02 4.800e+02 1.682e+03 1.358e+03 4.830e+02 6.720e+02 6.620e+02
 3.700e+02 7.120e+02 1.070e+03 5.280e+02 4.220e+02 9.400e+01 3.480e+02
 3.830e+02 1.330e+02 2.030e+02 2.180e+02 2.380e+02 4.260e+02 3.750e+02
 2.750e+02 1.406e+03 3.430e+02 7.600e+01 1.247e+03 7.350e+02 3.080e+02
 6.150e+02 6.790e+02 5.390e+02 7.800e+01 6.240e+02 4.200e+01 3.340e+02
 9.150e+02 1.290e+02 1.500e+02 2.940e+02 4.690e+02 5.930e+02 2.070e+02
 4.580e+02 4.760e+02 1.341e+03 5.640e+02 8.440e+02 1.410e+03 8.470e+02
 8.500e+02 2.840e+02 1.320e+03 1.965e+03 1.158e+03 3.410e+02 7.410e+02
 1.890e+02 3.100e+02 5.600e+02 6.940e+02 1.036e+03 1.904e+03 1.274e+03
 4.000e+02 6.920e+02 8.220e+02 1.246e+03 3.630e+02 8.320e+02 1.104e+03
 3.810e+02 6.220e+02 5.440e+02 2.250e+02 1.333e+03 8.880e+02 6.360e+02
 8.280e+02 4.390e+02 5.000e+02 7.260e+02 1.910e+02 2.540e+02 7.650e+02
 1.620e+02 2.310e+02 9.580e+02 3.060e+02 5.660e+02 4.350e+02 2.570e+02
 3.890e+02 2.790e+02 5.360e+02 6.440e+02 1.172e+03 1.360e+03 1.767e+03
 1.572e+03 9.860e+02 1.232e+03 1.436e+03 1.338e+03 2.288e+03 1.531e+03
 1.230e+03 1.015e+03 1.088e+03 1.037e+03 1.142e+03 1.170e+03 1.039e+03
 1.124e+03 1.262e+03 5.600e+01 1.972e+03 8.360e+02 9.000e+02 8.810e+02
 8.760e+02 9.040e+02 2.146e+03 1.557e+03 8.000e+02 1.196e+03 8.630e+02
 5.670e+02 9.880e+02 4.250e+02 6.520e+02 4.940e+02 6.510e+02 2.410e+02
 6.830e+02 9.130e+02 7.720e+02 1.163e+03 6.890e+02 1.173e+03 7.810e+02
 8.540e+02 2.360e+02 9.870e+02 1.361e+03 5.950e+02 1.294e+03 3.790e+02
 2.158e+03 2.700e+01 1.121e+03 6.820e+02 8.120e+02 1.430e+03 4.100e+02
 7.710e+02 5.400e+01 5.160e+02 9.760e+02 2.000e+01 5.200e+01 3.310e+02
 6.800e+01 6.600e+02 8.640e+02 5.940e+02 1.400e+02 1.733e+03 6.010e+02
 9.620e+02 5.490e+02 6.490e+02 1.252e+03 1.210e+02 1.116e+03 2.980e+02
 8.590e+02 9.550e+02 1.440e+02 6.430e+02 2.510e+02 4.030e+02 6.120e+02
 1.960e+02 9.980e+02 7.400e+02 3.880e+02 9.910e+02 5.680e+02 1.000e+02
 1.850e+02 1.024e+03 1.285e+03 6.070e+02 1.312e+03 6.090e+02 1.387e+03
 4.540e+02 7.080e+02 6.200e+02 5.850e+02 1.720e+02 1.550e+02 1.213e+03
 4.900e+02 4.280e+02 6.500e+02 7.000e+02 9.310e+02 4.400e+02 6.990e+02
 3.900e+02 6.800e+02 3.150e+02 3.840e+02 8.720e+02 7.450e+02 5.460e+02
 1.270e+03 6.210e+02 1.800e+02 6.300e+02 4.330e+02 1.148e+03 9.410e+02
 8.260e+02 6.330e+02 4.210e+02 3.120e+02 2.160e+02 4.950e+02 1.309e+03
 2.200e+02 4.050e+02 2.090e+02 2.730e+02 1.340e+02 2.990e+02 5.220e+02
 1.520e+02 1.690e+02 7.490e+02 1.152e+03 3.500e+02 5.510e+02 4.440e+02
 2.260e+02 5.270e+02 6.850e+02 1.700e+02 1.324e+03 2.620e+02 3.420e+02
 3.440e+02 1.730e+02 5.520e+02 2.920e+02 2.040e+02 4.600e+02 7.000e+01
 1.441e+03 4.850e+02 5.130e+02 5.840e+02 1.086e+03 1.094e+03 8.200e+02
 1.021e+03 1.288e+03 1.359e+03 1.334e+03 9.020e+02 7.240e+02 1.518e+03
 2.490e+02 7.320e+02 7.550e+02 8.210e+02 3.850e+02 9.500e+02 7.460e+02
 6.060e+02 6.660e+02 1.259e+03 7.100e+02 6.460e+02 7.770e+02 1.234e+03
 9.900e+02 6.900e+02 1.111e+03 1.478e+03 1.930e+02 5.350e+02 3.990e+02
 6.310e+02 5.470e+02 3.320e+02 6.260e+02 4.080e+02 2.900e+02 5.230e+02
 7.930e+02 7.130e+02 2.460e+02 1.540e+02 6.500e+01 7.840e+02 4.710e+02
 2.850e+02 8.030e+02 8.080e+02 1.476e+03 4.450e+02 1.351e+03 7.670e+02
 6.110e+02 5.500e+01 1.110e+02 1.236e+03 1.022e+03 1.758e+03 1.115e+03
 1.005e+03 4.620e+02 1.260e+03 1.640e+03 8.660e+02 8.830e+02 5.150e+02
 5.090e+02 7.200e+02 1.140e+02 1.097e+03 7.180e+02 3.300e+02 1.567e+03
 4.960e+02 8.650e+02 7.060e+02 8.510e+02 1.380e+02 1.153e+03 2.190e+02
 3.190e+02 1.337e+03 1.034e+03 9.830e+02 1.206e+03 8.960e+02 8.900e+02
 1.084e+03 1.023e+03 2.520e+02 1.190e+02 2.660e+02 3.210e+02 3.870e+02
 3.580e+02 5.590e+02 2.860e+02 1.336e+03 1.280e+03 1.636e+03 1.330e+03
 1.012e+03 1.400e+03 1.728e+03 1.375e+03 1.420e+03 1.082e+03 1.249e+03
 4.000e+01 2.257e+03 1.016e+03 1.149e+03 1.075e+03 3.720e+02 1.540e+03
 1.204e+03 8.460e+02 5.730e+02 1.073e+03 1.087e+03 7.590e+02 6.550e+02
 1.660e+03 1.696e+03 2.280e+02 1.314e+03 1.096e+03 3.300e+01 7.290e+02
 7.890e+02 5.030e+02 8.000e+01 8.140e+02 3.620e+02 1.138e+03 5.370e+02
 4.720e+02 3.970e+02 1.650e+02 5.300e+01 7.370e+02 7.640e+02 4.890e+02
 1.900e+02 5.200e+02 5.500e+02 1.027e+03 1.004e+03 1.141e+03 1.238e+03
 6.810e+02 8.130e+02 1.280e+02 7.860e+02 1.619e+03 1.044e+03 3.010e+02
 6.030e+02 9.560e+02 2.600e+02 5.830e+02 5.750e+02 8.670e+02 7.760e+02
 8.920e+02 7.870e+02 8.060e+02 4.190e+02 6.580e+02 3.200e+01 8.310e+02
 5.310e+02 5.720e+02 2.500e+01 1.053e+03 1.040e+03 5.700e+02 7.740e+02
 1.480e+02 8.520e+02 5.800e+02 7.440e+02 3.740e+02 6.730e+02 9.600e+01
 4.930e+02 5.900e+02 1.160e+02 1.410e+02 2.590e+02 2.000e+02 4.060e+02
 1.750e+02 5.210e+02 2.010e+02       nan 3.360e+02 2.100e+02 3.510e+02
 9.060e+02 7.580e+02 7.020e+02 2.210e+02 1.198e+03 1.300e+03 6.340e+02
 1.064e+03 4.290e+02 1.003e+03 3.920e+02 5.990e+02 7.190e+02 1.035e+03
 3.240e+02 9.690e+02 1.085e+03 7.790e+02 1.271e+03 3.550e+02 2.085e+03
 5.000e+01 7.700e+02 7.220e+02 1.308e+03 6.880e+02 3.610e+02 6.630e+02
 4.860e+02 8.800e+01 6.320e+02 6.680e+02 1.194e+03 1.538e+03 6.420e+02
 9.940e+02 1.593e+03 8.100e+02 9.460e+02 8.300e+02 1.033e+03 9.200e+02
 5.644e+03 4.590e+02 3.520e+02 2.240e+02 4.100e+01 4.230e+02 2.810e+02
 3.660e+02 8.100e+01 5.380e+02 1.480e+03 1.474e+03 6.410e+02 1.383e+03
 8.930e+02 1.165e+03 1.513e+03 1.398e+03 7.830e+02 1.029e+03 1.223e+03
 8.710e+02 1.011e+03 1.571e+03 7.690e+02 3.180e+02 5.010e+02 4.370e+02
 7.850e+02 5.340e+02 6.380e+02 6.470e+02 5.620e+02 8.380e+02 7.780e+02
 1.880e+03 1.860e+02 4.140e+02 9.260e+02 1.101e+03 1.047e+03 7.970e+02
 9.450e+02 1.558e+03 6.780e+02 2.560e+02 1.328e+03 6.050e+02 9.030e+02
 4.920e+02 3.490e+02 2.820e+02 4.120e+02 3.220e+02 3.140e+02 9.300e+02
 3.560e+02 5.560e+02 7.250e+02 1.151e+03 1.304e+03 1.812e+03 1.350e+03
 1.684e+03 9.700e+02 9.380e+02 6.690e+02 1.178e+03 1.030e+03 7.620e+02
 8.480e+02 9.180e+02 5.740e+02 2.096e+03 1.181e+03 1.282e+03 1.048e+03
 1.455e+03 8.620e+02 5.650e+02 1.231e+03 3.350e+02 1.225e+03 1.220e+03

In [29]:
for col in df.columns:
    print(f"{df[col].nunique()}")

2930
16
7
128
1960
2
2
4
4
3
5
3
28
9
8
5
8
10
9
118
61
6
8
16
17
4
445
4
5
6
5
5
4
6
995
6
274
1137
1058
6
5
2
5
1083
635
36
1292
4
3
5
3
8
4
5
14
8
5
5
6
103
3
6
603
5
5
3
380
252
183
31
121
14
4
4
5
38
12
5
10
6
1032

In [30]:
for col in df.columns:
    print(df[col].count())

2930
2930
2930
2440
2930
2930
198
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
2930
1155
2907
2930
2930
2930
2850
2850
2847
2850
2929
2849
2929
2929
2929
2930
2930
2930
2929
2930
2930
2930
2930
2928
2928
2930
2930
2930
2930
2930
2930
2930
2930
1508
2773
2771
2771
2929
2929
2771
2771
2930
2930
2930
2930
2930
2930
2930
13
572
106
2930
2930
2930
2930
2930
2930

In [34]:
for col in df.columns:
    print(f"{col}: {(1- df[col].count()/len(df)) * 100:.2f}%")

PID: 0.00%
MS SubClass: 0.00%
MS Zoning: 0.00%
Lot Frontage: 16.72%
Lot Area: 0.00%
Street: 0.00%
Alley: 93.24%
Lot Shape: 0.00%
Land Contour: 0.00%
Utilities: 0.00%
Lot Config: 0.00%
Land Slope: 0.00%
Neighborhood: 0.00%
Condition 1: 0.00%
Condition 2: 0.00%
Bldg Type: 0.00%
House Style: 0.00%
Overall Qual: 0.00%
Overall Cond: 0.00%
Year Built: 0.00%
Year Remod/Add: 0.00%
Roof Style: 0.00%
Roof Matl: 0.00%
Exterior 1st: 0.00%
Exterior 2nd: 0.00%
Mas Vnr Type: 60.58%
Mas Vnr Area: 0.78%
Exter Qual: 0.00%
Exter Cond: 0.00%
Foundation: 0.00%
Bsmt Qual: 2.73%
Bsmt Cond: 2.73%
Bsmt Exposure: 2.83%
BsmtFin Type 1: 2.73%
BsmtFin SF 1: 0.03%
BsmtFin Type 2: 2.76%
BsmtFin SF 2: 0.03%
Bsmt Unf SF: 0.03%
Total Bsmt SF: 0.03%
Heating: 0.00%
Heating QC: 0.00%
Central Air: 0.00%
Electrical: 0.03%
1st Flr SF: 0.00%
2nd Flr SF: 0.00%
Low Qual Fin SF: 0.00%
Gr Liv Area: 0.00%
Bsmt Full Bath: 0.07%
Bsmt Half Bath: 0.07%
Full Bath: 0.00%
Half Bath: 0.00%
Bedroom AbvGr: 0.00%
Kitchen AbvGr: 0.00%
Kitchen Qual: 0.00%
TotRms AbvGrd: 0.00%
Functional: 0.00%
Fireplaces: 0.00%
Fireplace Qu: 48.53%
Garage Type: 5.36%
Garage Yr Blt: 5.43%
Garage Finish: 5.43%
Garage Cars: 0.03%
Garage Area: 0.03%
Garage Qual: 5.43%
Garage Cond: 5.43%
Paved Drive: 0.00%
Wood Deck SF: 0.00%
Open Porch SF: 0.00%
Enclosed Porch: 0.00%
3Ssn Porch: 0.00%
Screen Porch: 0.00%
Pool Area: 0.00%
Pool QC: 99.56%
Fence: 80.48%
Misc Feature: 96.38%
Misc Val: 0.00%
Mo Sold: 0.00%
Yr Sold: 0.00%
Sale Type: 0.00%
Sale Condition: 0.00%
SalePrice: 0.00%

In [35]:
for col in df.columns:
    print(f"{(1- df[col].count()/len(df)) * 100:.2f}%")

0.00%
0.00%
0.00%
16.72%
0.00%
0.00%
93.24%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
60.58%
0.78%
0.00%
0.00%
0.00%
2.73%
2.73%
2.83%
2.73%
0.03%
2.76%
0.03%
0.03%
0.03%
0.00%
0.00%
0.00%
0.03%
0.00%
0.00%
0.00%
0.00%
0.07%
0.07%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
48.53%
5.36%
5.43%
5.43%
0.03%
0.03%
5.43%
5.43%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%
99.56%
80.48%
96.38%
0.00%
0.00%
0.00%
0.00%
0.00%
0.00%

In [37]:
summary_table = pd.DataFrame({
    'Num of Values': df.count(),
    '% of Missing Values': df.isnull().mean() * 100,
    'Unique Values (Categorical)': df.select_dtypes(include=['object', 'string']).nunique(),
    'Mean (Numerical)': df.select_dtypes(include='number').mean(),
    'Python Type': df.dtypes,
})

summary_table

,Num of Values,% of Missing Values,Unique Values (Categorical),Mean (Numerical),Python Type
1st Flr SF,2930,0.000000,NaN,1159.557679,int64
2nd Flr SF,2930,0.000000,NaN,335.455973,int64
3Ssn Porch,2930,0.000000,NaN,2.592491,int64
Alley,198,93.242321,2.0,NaN,str
Bedroom AbvGr,2930,0.000000,NaN,2.854266,int64
...,...,...,...,...,...
Utilities,2930,0.000000,3.0,NaN,str
Wood Deck SF,2930,0.000000,NaN,93.751877,int64
Year Built,2930,0.000000,NaN,1971.356314,int64
Year Remod/Add,2930,0.000000,NaN,1984.266553,int64
Yr Sold,2930,0.000000,NaN,2007.790444,int64