In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:.2f}'.format

# Dataset loading

In [3]:
data_path = r"C:\Users\erica\Documents\Mestrado\Projetos\Advanced_DS\Ames_Housing_Project\data\raw\AmesHousing.csv"
df = pd.read_csv(data_path)
pd.set_option('display.max_columns', None)
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.00,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,5,1960,1960,Hip,CompShg,BrkFace,Plywood,Stone,112.00,TA,TA,CBlock,TA,Gd,Gd,BLQ,639.00,Unf,0.00,441.00,1080.00,GasA,Fa,Y,SBrkr,1656,0,0,1656,1.00,0.00,1,0,3,1,TA,7,Typ,2,Gd,Attchd,1960.00,Fin,2.00,528.00,TA,TA,P,210,62,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.00,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,5,6,1961,1961,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,CBlock,TA,TA,No,Rec,468.00,LwQ,144.00,270.00,882.00,GasA,TA,Y,SBrkr,896,0,0,896,0.00,0.00,1,0,2,1,TA,5,Typ,0,NaN,Attchd,1961.00,Unf,1.00,730.00,TA,TA,Y,140,0,0,0,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.00,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,6,6,1958,1958,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,108.00,TA,TA,CBlock,TA,TA,No,ALQ,923.00,Unf,0.00,406.00,1329.00,GasA,TA,Y,SBrkr,1329,0,0,1329,0.00,0.00,1,1,3,1,Gd,6,Typ,0,NaN,Attchd,1958.00,Unf,1.00,312.00,TA,TA,Y,393,36,0,0,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.00,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,NAmes,Norm,Norm,1Fam,1Story,7,5,1968,1968,Hip,CompShg,BrkFace,BrkFace,NaN,0.00,Gd,TA,CBlock,TA,TA,No,ALQ,1065.00,Unf,0.00,1045.00,2110.00,GasA,Ex,Y,SBrkr,2110,0,0,2110,1.00,0.00,2,1,3,1,Ex,8,Typ,2,TA,Attchd,1968.00,Fin,2.00,522.00,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.00,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,5,5,1997,1998,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,PConc,Gd,TA,No,GLQ,791.00,Unf,0.00,137.00,928.00,GasA,Gd,Y,SBrkr,928,701,0,1629,0.00,0.00,2,1,3,1,TA,6,Typ,1,TA,Attchd,1997.00,Fin,2.00,482.00,TA,TA,Y,212,34,0,0,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

# Exploratory Data Analisys

## Descriptive statistics

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   str
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot Shape        2930 non-null   str
 9   Land Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot Config       2930 non-null   str
 12  Land Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition 1      2930 non-null   str
 15  Condition 2      2930 non-null   str
 16  Bldg Type        2930 non-null   str
 17  House Style      2930 non-null   str
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   str
 23  Roof Matl        2930 non-null   str
 24  Exterior 1st     2930 non-null   str
 25  Exterior 2nd     2930 non-null   str
 26  Mas Vnr Type     1155 non-null   str
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   str
 29  Exter Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt Qual        2850 non-null   str
 32  Bsmt Cond        2850 non-null   str
 33  Bsmt Exposure    2847 non-null   str
 34  BsmtFin Type 1   2850 non-null   str
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   str
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating QC       2930 non-null   str
 42  Central Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   str
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   str
 59  Garage Type      2773 non-null   str
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   str
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   str
 65  Garage Cond      2771 non-null   str
 66  Paved Drive      2930 non-null   str
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc Feature     106 non-null    str
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   str
 80  Sale Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 1.8 MB

In [5]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,TotRms AbvGrd,Fireplaces,Garage Yr Blt,Garage Cars,Garage Area,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00,2930.00,2930.00,2440.00,2930.00,2930.00,2930.00,2930.00,2930.00,2907.00,2929.00,2929.00,2929.00,2929.00,2930.00,2930.00,2930.00,2930.00,2928.00,2928.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00,2771.00,2929.00,2929.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00,2930.00
mean,1465.50,714464496.99,57.39,69.22,10147.92,6.09,5.56,1971.36,1984.27,101.90,442.63,49.72,559.26,1051.61,1159.56,335.46,4.68,1499.69,0.43,0.06,1.57,0.38,2.85,1.04,6.44,0.60,1978.13,1.77,472.82,93.75,47.53,23.01,2.59,16.00,2.24,50.64,6.22,2007.79,180796.06
std,845.96,188730844.65,42.64,23.37,7880.02,1.41,1.11,30.25,20.86,179.11,455.59,169.17,439.49,440.62,391.89,428.40,46.31,505.51,0.52,0.25,0.55,0.50,0.83,0.21,1.57,0.65,25.53,0.76,215.05,126.36,67.48,64.14,25.14,56.09,35.60,566.34,2.71,1.32,79886.69
min,1.00,526301100.00,20.00,21.00,1300.00,1.00,1.00,1872.00,1950.00,0.00,0.00,0.00,0.00,0.00,334.00,0.00,0.00,334.00,0.00,0.00,0.00,0.00,0.00,0.00,2.00,0.00,1895.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,2006.00,12789.00
25%,733.25,528477022.50,20.00,58.00,7440.25,5.00,5.00,1954.00,1965.00,0.00,0.00,0.00,219.00,793.00,876.25,0.00,0.00,1126.00,0.00,0.00,1.00,0.00,2.00,1.00,5.00,0.00,1960.00,1.00,320.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.00,2007.00,129500.00
50%,1465.50,535453620.00,50.00,68.00,9436.50,6.00,5.00,1973.00,1993.00,0.00,370.00,0.00,466.00,990.00,1084.00,0.00,0.00,1442.00,0.00,0.00,2.00,0.00,3.00,1.00,6.00,1.00,1979.00,2.00,480.00,0.00,27.00,0.00,0.00,0.00,0.00,0.00,6.00,2008.00,160000.00
75%,2197.75,907181097.50,70.00,80.00,11555.25,7.00,6.00,2001.00,2004.00,164.00,734.00,0.00,802.00,1302.00,1384.00,703.75,0.00,1742.75,1.00,0.00,2.00,1.00,3.00,1.00,7.00,1.00,2002.00,2.00,576.00,168.00,70.00,0.00,0.00,0.00,0.00,0.00,8.00,2009.00,213500.00
max,2930.00,1007100110.00,190.00,313.00,215245.00,10.00,9.00,2010.00,2010.00,1600.00,5644.00,1526.00,2336.00,6110.00,5095.00,2065.00,1064.00,5642.00,3.00,2.00,4.00,2.00,8.00,3.00,15.00,4.00,2207.00,5.00,1488.00,1424.00,742.00,1012.00,508.00,576.00,800.00,17000.00,12.00,2010.00,755000.00

In [6]:
print(f"Quantidade de linhas: {df.shape[0]}")
print(f"Quantidade de colunas: {df.shape[1]}")

Quantidade de linhas: 2930
Quantidade de colunas: 82

## Tabelas

In [7]:
summary_table = pd.DataFrame({
    'Num of Values': df.count(),
    '% of Missing Values': df.isnull().mean() * 100,
    'Unique Values (Categorical)': df.select_dtypes(include=['object', 'string']).nunique(),
    'Mean (Numerical)': df.select_dtypes(include='number').mean(),
    'Python Type': df.dtypes,
})

pd.set_option('display.max_rows', None)
summary_table

,Num of Values,% of Missing Values,Unique Values (Categorical),Mean (Numerical),Python Type
1st Flr SF,2930,0.00,NaN,1159.56,int64
2nd Flr SF,2930,0.00,NaN,335.46,int64
3Ssn Porch,2930,0.00,NaN,2.59,int64
Alley,198,93.24,2.00,NaN,str
Bedroom AbvGr,2930,0.00,NaN,2.85,int64
Bldg Type,2930,0.00,5.00,NaN,str
Bsmt Cond,2850,2.73,5.00,NaN,str
Bsmt Exposure,2847,2.83,4.00,NaN,str
Bsmt Full Bath,2928,0.07,NaN,0.43,float64
Bsmt Half Bath,2928,0.07,NaN,0.06,float64
Bsmt Qual,2850,2.73,5.00,NaN,str
Bsmt Unf SF,2929,0.03,NaN,559.26,float64
BsmtFin SF 1,2929,0.03,NaN,442.63,float64
BsmtFin SF 2,2929,0.03,NaN,49.72,float64
BsmtFin Type 1,2850,2.73,6.00,NaN,str
BsmtFin Type 2,2849,2.76,6.00,NaN,str
Central Air,2930,0.00,2.00,NaN,str
Condition 1,2930,0.00,9.00,NaN,str
Condition 2,2930,0.00,8.00,NaN,str
Electrical,2929,0.03,5.00,NaN,str
Enclosed Porch,2930,0.00,NaN,23.01,int64
Exter Cond,2930,0.00,5.00,NaN,str
Exter Qual,2930,0.00,4.00,NaN,str
Exterior 1st,2930,0.00,16.00,NaN,str
Exterior 2nd,2930,0.00,17.00,NaN,str
Fence,572,80.48,4.00,NaN,str
Fireplace Qu,1508,48.53,5.00,NaN,str
Fireplaces,2930,0.00,NaN,0.60,int64
Foundation,2930,0.00,6.00,NaN,str
Full Bath,2930,0.00,NaN,1.57,int64
Functional,2930,0.00,8.00,NaN,str
Garage Area,2929,0.03,NaN,472.82,float64
Garage Cars,2929,0.03,NaN,1.77,float64
Garage Cond,2771,5.43,5.00,NaN,str
Garage Finish,2771,5.43,3.00,NaN,str
Garage Qual,2771,5.43,5.00,NaN,str
Garage Type,2773,5.36,6.00,NaN,str
Garage Yr Blt,2771,5.43,NaN,1978.13,float64
Gr Liv Area,2930,0.00,NaN,1499.69,int64
Half Bath,2930,0.00,NaN,0.38,int64
Heating,2930,0.00,6.00,NaN,str
Heating QC,2930,0.00,5.00,NaN,str
House Style,2930,0.00,8.00,NaN,str
Kitchen AbvGr,2930,0.00,NaN,1.04,int64
Kitchen Qual,2930,0.00,5.00,NaN,str
Land Contour,2930,0.00,4.00,NaN,str
Land Slope,2930,0.00,3.00,NaN,str
Lot Area,2930,0.00,NaN,10147.92,int64
Lot Config,2930,0.00,5.00,NaN,str
Lot Frontage,2440,16.72,NaN,69.22,float64
Lot Shape,2930,0.00,4.00,NaN,str
Low Qual Fin SF,2930,0.00,NaN,4.68,int64
MS SubClass,2930,0.00,NaN,57.39,int64
MS Zoning,2930,0.00,7.00,NaN,str
Mas Vnr Area,2907,0.78,NaN,101.90,float64
Mas Vnr Type,1155,60.58,4.00,NaN,str
Misc Feature,106,96.38,5.00,NaN,str
Misc Val,2930,0.00,NaN,50.64,int64
Mo Sold,2930,0.00,NaN,6.22,int64
Neighborhood,2930,0.00,28.00,NaN,str
Open Porch SF,2930,0.00,NaN,47.53,int64
Order,2930,0.00,NaN,1465.50,int64
Overall Cond,2930,0.00,NaN,5.56,int64
Overall Qual,2930,0.00,NaN,6.09,int64
PID,2930,0.00,NaN,714464496.99,int64
Paved Drive,2930,0.00,3.00,NaN,str
Pool Area,2930,0.00,NaN,2.24,int64
Pool QC,13,99.56,4.00,NaN,str
Roof Matl,2930,0.00,8.00,NaN,str
Roof Style,2930,0.00,6.00,NaN,str
Sale Condition,2930,0.00,6.00,NaN,str
Sale Type,2930,0.00,10.00,NaN,str
SalePrice,2930,0.00,NaN,180796.06,int64
Screen Porch,2930,0.00,NaN,16.00,int64
Street,2930,0.00,2.00,NaN,str
TotRms AbvGrd,2930,0.00,NaN,6.44,int64
Total Bsmt SF,2929,0.03,NaN,1051.61,float64
Utilities,2930,0.00,3.00,NaN,str
Wood Deck SF,2930,0.00,NaN,93.75,int64
Year Built,2930,0.00,NaN,1971.36,int64
Year Remod/Add,2930,0.00,NaN,1984.27,int64
Yr Sold,2930,0.00,NaN,2007.79,int64

### Variáveis numéricas

In [8]:
numerical_cols = df.select_dtypes(include='number').columns

In [9]:
numerical_summary = pd.DataFrame({
    'Tipo': df[numerical_cols].dtypes,
    'Média': df[numerical_cols].mean(),
    'Mediana': df[numerical_cols].median(),
    'Desvio Padrão': df[numerical_cols].std(),
    'Mínimo': df[numerical_cols].min(),
    'Máximo': df[numerical_cols].max(),
})

numerical_summary

,Tipo,Média,Mediana,Desvio Padrão,Mínimo,Máximo
Order,int64,1465.50,1465.50,845.96,1.00,2930.00
PID,int64,714464496.99,535453620.00,188730844.65,526301100.00,1007100110.00
MS SubClass,int64,57.39,50.00,42.64,20.00,190.00
Lot Frontage,float64,69.22,68.00,23.37,21.00,313.00
Lot Area,int64,10147.92,9436.50,7880.02,1300.00,215245.00
Overall Qual,int64,6.09,6.00,1.41,1.00,10.00
Overall Cond,int64,5.56,5.00,1.11,1.00,9.00
Year Built,int64,1971.36,1973.00,30.25,1872.00,2010.00
Year Remod/Add,int64,1984.27,1993.00,20.86,1950.00,2010.00
Mas Vnr Area,float64,101.90,0.00,179.11,0.00,1600.00
BsmtFin SF 1,float64,442.63,370.00,455.59,0.00,5644.00
BsmtFin SF 2,float64,49.72,0.00,169.17,0.00,1526.00
Bsmt Unf SF,float64,559.26,466.00,439.49,0.00,2336.00
Total Bsmt SF,float64,1051.61,990.00,440.62,0.00,6110.00
1st Flr SF,int64,1159.56,1084.00,391.89,334.00,5095.00
2nd Flr SF,int64,335.46,0.00,428.40,0.00,2065.00
Low Qual Fin SF,int64,4.68,0.00,46.31,0.00,1064.00
Gr Liv Area,int64,1499.69,1442.00,505.51,334.00,5642.00
Bsmt Full Bath,float64,0.43,0.00,0.52,0.00,3.00
Bsmt Half Bath,float64,0.06,0.00,0.25,0.00,2.00
Full Bath,int64,1.57,2.00,0.55,0.00,4.00
Half Bath,int64,0.38,0.00,0.50,0.00,2.00
Bedroom AbvGr,int64,2.85,3.00,0.83,0.00,8.00
Kitchen AbvGr,int64,1.04,1.00,0.21,0.00,3.00
TotRms AbvGrd,int64,6.44,6.00,1.57,2.00,15.00
Fireplaces,int64,0.60,1.00,0.65,0.00,4.00
Garage Yr Blt,float64,1978.13,1979.00,25.53,1895.00,2207.00
Garage Cars,float64,1.77,2.00,0.76,0.00,5.00
Garage Area,float64,472.82,480.00,215.05,0.00,1488.00
Wood Deck SF,int64,93.75,0.00,126.36,0.00,1424.00
Open Porch SF,int64,47.53,27.00,67.48,0.00,742.00
Enclosed Porch,int64,23.01,0.00,64.14,0.00,1012.00
3Ssn Porch,int64,2.59,0.00,25.14,0.00,508.00
Screen Porch,int64,16.00,0.00,56.09,0.00,576.00
Pool Area,int64,2.24,0.00,35.60,0.00,800.00
Misc Val,int64,50.64,0.00,566.34,0.00,17000.00
Mo Sold,int64,6.22,6.00,2.71,1.00,12.00
Yr Sold,int64,2007.79,2008.00,1.32,2006.00,2010.00
SalePrice,int64,180796.06,160000.00,79886.69,12789.00,755000.00

In [10]:
numerical_summary.sort_values(by='Desvio Padrão', ascending=False)

,Tipo,Média,Mediana,Desvio Padrão,Mínimo,Máximo
PID,int64,714464496.99,535453620.00,188730844.65,526301100.00,1007100110.00
SalePrice,int64,180796.06,160000.00,79886.69,12789.00,755000.00
Lot Area,int64,10147.92,9436.50,7880.02,1300.00,215245.00
Order,int64,1465.50,1465.50,845.96,1.00,2930.00
Misc Val,int64,50.64,0.00,566.34,0.00,17000.00
Gr Liv Area,int64,1499.69,1442.00,505.51,334.00,5642.00
BsmtFin SF 1,float64,442.63,370.00,455.59,0.00,5644.00
Total Bsmt SF,float64,1051.61,990.00,440.62,0.00,6110.00
Bsmt Unf SF,float64,559.26,466.00,439.49,0.00,2336.00
2nd Flr SF,int64,335.46,0.00,428.40,0.00,2065.00
1st Flr SF,int64,1159.56,1084.00,391.89,334.00,5095.00
Garage Area,float64,472.82,480.00,215.05,0.00,1488.00
Mas Vnr Area,float64,101.90,0.00,179.11,0.00,1600.00
BsmtFin SF 2,float64,49.72,0.00,169.17,0.00,1526.00
Wood Deck SF,int64,93.75,0.00,126.36,0.00,1424.00
Open Porch SF,int64,47.53,27.00,67.48,0.00,742.00
Enclosed Porch,int64,23.01,0.00,64.14,0.00,1012.00
Screen Porch,int64,16.00,0.00,56.09,0.00,576.00
Low Qual Fin SF,int64,4.68,0.00,46.31,0.00,1064.00
MS SubClass,int64,57.39,50.00,42.64,20.00,190.00
Pool Area,int64,2.24,0.00,35.60,0.00,800.00
Year Built,int64,1971.36,1973.00,30.25,1872.00,2010.00
Garage Yr Blt,float64,1978.13,1979.00,25.53,1895.00,2207.00
3Ssn Porch,int64,2.59,0.00,25.14,0.00,508.00
Lot Frontage,float64,69.22,68.00,23.37,21.00,313.00
Year Remod/Add,int64,1984.27,1993.00,20.86,1950.00,2010.00
Mo Sold,int64,6.22,6.00,2.71,1.00,12.00
TotRms AbvGrd,int64,6.44,6.00,1.57,2.00,15.00
Overall Qual,int64,6.09,6.00,1.41,1.00,10.00
Yr Sold,int64,2007.79,2008.00,1.32,2006.00,2010.00
Overall Cond,int64,5.56,5.00,1.11,1.00,9.00
Bedroom AbvGr,int64,2.85,3.00,0.83,0.00,8.00
Garage Cars,float64,1.77,2.00,0.76,0.00,5.00
Fireplaces,int64,0.60,1.00,0.65,0.00,4.00
Full Bath,int64,1.57,2.00,0.55,0.00,4.00
Bsmt Full Bath,float64,0.43,0.00,0.52,0.00,3.00
Half Bath,int64,0.38,0.00,0.50,0.00,2.00
Bsmt Half Bath,float64,0.06,0.00,0.25,0.00,2.00
Kitchen AbvGr,int64,1.04,1.00,0.21,0.00,3.00

### Variáveis Categóricas

In [11]:
catergorical_cols = df.select_dtypes(include=['object', 'string']).columns

In [12]:
categorical_summary = pd.DataFrame({
    'Valores Únicos': df[catergorical_cols].nunique(),
    'Valor Mais Frequente': df[catergorical_cols].mode().iloc[0],
    'Frequência do Valor Mais Frequente': df[catergorical_cols].apply(lambda x: x.value_counts().iloc[0]),
    'Porcentagem do Valor Mais Frequente': df[catergorical_cols].apply(lambda x: x.value_counts(normalize=True).iloc[0] * 100)
})
categorical_summary.sort_values(by='Valores Únicos', ascending=False)

,Valores Únicos,Valor Mais Frequente,Frequência do Valor Mais Frequente,Porcentagem do Valor Mais Frequente
Neighborhood,28,NAmes,443,15.12
Exterior 2nd,17,VinylSd,1015,34.64
Exterior 1st,16,VinylSd,1026,35.02
Sale Type,10,WD,2536,86.55
Condition 1,9,Norm,2522,86.08
House Style,8,1Story,1481,50.55
Functional,8,Typ,2728,93.11
Roof Matl,8,CompShg,2887,98.53
Condition 2,8,Norm,2900,98.98
MS Zoning,7,RL,2273,77.58
Roof Style,6,Gable,2321,79.22
BsmtFin Type 1,6,GLQ,859,30.14
Sale Condition,6,Normal,2413,82.35
Heating,6,GasA,2885,98.46
Foundation,6,PConc,1310,44.71
Garage Type,6,Attchd,1731,62.42
BsmtFin Type 2,6,Unf,2499,87.71
Lot Config,5,Inside,2140,73.04
Kitchen Qual,5,TA,1494,50.99
Misc Feature,5,Shed,95,89.62
Garage Cond,5,TA,2665,96.17
Garage Qual,5,TA,2615,94.37
Exter Cond,5,TA,2549,87.00
Fireplace Qu,5,Gd,744,49.34
Bsmt Cond,5,TA,2616,91.79
Bldg Type,5,1Fam,2425,82.76
Bsmt Qual,5,TA,1283,45.02
Heating QC,5,Ex,1495,51.02
Electrical,5,SBrkr,2682,91.57
Bsmt Exposure,4,No,1906,66.95
Exter Qual,4,TA,1799,61.40
Land Contour,4,Lvl,2633,89.86
Lot Shape,4,Reg,1859,63.45
Mas Vnr Type,4,BrkFace,880,76.19
Pool QC,4,Ex,4,30.77
Fence,4,MnPrv,330,57.69
Garage Finish,3,Unf,1231,44.42
Land Slope,3,Gtl,2789,95.19
Utilities,3,AllPub,2927,99.90
Paved Drive,3,Y,2652,90.51
Alley,2,Grvl,120,60.61
Street,2,Pave,2918,99.59
Central Air,2,Y,2734,93.31

## Missing Values

In [13]:
varibles_with_missing_values = summary_table[summary_table['% of Missing Values'] > 0].T.columns
varibles_with_missing_values

Index(['Alley', 'Bsmt Cond', 'Bsmt Exposure', 'Bsmt Full Bath',
       'Bsmt Half Bath', 'Bsmt Qual', 'Bsmt Unf SF', 'BsmtFin SF 1',
       'BsmtFin SF 2', 'BsmtFin Type 1', 'BsmtFin Type 2', 'Electrical',
       'Fence', 'Fireplace Qu', 'Garage Area', 'Garage Cars', 'Garage Cond',
       'Garage Finish', 'Garage Qual', 'Garage Type', 'Garage Yr Blt',
       'Lot Frontage', 'Mas Vnr Area', 'Mas Vnr Type', 'Misc Feature',
       'Pool QC', 'Total Bsmt SF'],
      dtype='str')

In [14]:
for col in varibles_with_missing_values:
    print(f"{col}:\n {df[col].isnull().sum()} missing values")
    print(f"Percentage: {df[col].isnull().mean() * 100:.2f}%")
    print(f'{df[col].value_counts(dropna=False)}\n')
    print("-" * 40)

Alley:
 2732 missing values
Percentage: 93.24%
Alley
NaN     2732
Grvl     120
Pave      78
Name: count, dtype: int64

----------------------------------------
Bsmt Cond:
 80 missing values
Percentage: 2.73%
Bsmt Cond
TA     2616
Gd      122
Fa      104
NaN      80
Po        5
Ex        3
Name: count, dtype: int64

----------------------------------------
Bsmt Exposure:
 83 missing values
Percentage: 2.83%
Bsmt Exposure
No     1906
Av      418
Gd      284
Mn      239
NaN      83
Name: count, dtype: int64

----------------------------------------
Bsmt Full Bath:
 2 missing values
Percentage: 0.07%
Bsmt Full Bath
0.00    1707
1.00    1181
2.00      38
3.00       2
NaN        2
Name: count, dtype: int64

----------------------------------------
Bsmt Half Bath:
 2 missing values
Percentage: 0.07%
Bsmt Half Bath
0.00    2753
1.00     171
2.00       4
NaN        2
Name: count, dtype: int64

----------------------------------------
Bsmt Qual:
 80 missing values
Percentage: 2.73%
Bsmt Qual
TA     1283
Gd     1219
Ex      258
Fa       88
NaN      80
Po        2
Name: count, dtype: int64

----------------------------------------
Bsmt Unf SF:
 1 missing values
Percentage: 0.03%
Bsmt Unf SF
0.00       244
384.00      19
728.00      14
672.00      13
600.00      12
816.00      11
216.00      11
100.00      11
572.00      11
270.00      10
300.00      10
624.00      10
186.00       9
396.00       9
264.00       9
768.00       9
280.00       9
840.00       8
162.00       8
832.00       8
480.00       8
780.00       8
546.00       8
348.00       8
294.00       8
108.00       8
440.00       8
324.00       7
525.00       7
847.00       7
292.00       7
392.00       7
448.00       7
252.00       7
120.00       7
80.00        7
356.00       7
336.00       7
630.00       7
784.00       7
322.00       7
738.00       7
319.00       7
132.00       6
432.00       6
625.00       6
884.00       6
210.00       6
224.00       6
190.00       6
410.00       6
150.00       6
125.00       6
456.00       6
326.00       6
576.00       6
912.00       6
278.00       6
312.00       6
200.00       6
316.00       6
660.00       6
405.00       6
676.00       6
698.00       6
30.00        6
195.00       6
160.00       6
460.00       6
416.00       6
168.00       6
570.00       6
342.00       6
684.00       6
88.00        6
408.00       6
276.00       6
240.00       6
936.00       6
585.00       6
536.00       6
163.00       6
490.00       6
390.00       6
426.00       5
284.00       5
340.00       5
261.00       5
192.00       5
138.00       5
228.00       5
350.00       5
404.00       5
180.00       5
1008.00      5
747.00       5
360.00       5
90.00        5
172.00       5
140.00       5
176.00       5
960.00       5
641.00       5
894.00       5
434.00       5
212.00       5
36.00        5
166.00       5
476.00       5
598.00       5
115.00       5
250.00       5
484.00       5
474.00       5
130.00       5
422.00       5
420.00       5
306.00       5
785.00       5
504.00       5
245.00       5
952.00       5
248.00       5
596.00       5
96.00        5
556.00       5
638.00       5
226.00       5
796.00       5
686.00       5
970.00       5
441.00       4
744.00       4
354.00       4
544.00       4
235.00       4
628.00       4
253.00       4
594.00       4
381.00       4
76.00        4
378.00       4
92.00        4
286.00       4
491.00       4
174.00       4
143.00       4
386.00       4
533.00       4
173.00       4
482.00       4
662.00       4
380.00       4
188.00       4
710.00       4
756.00       4
346.00       4
455.00       4
308.00       4
689.00       4
232.00       4
204.00       4
328.00       4
564.00       4
218.00       4
741.00       4
1040.00      4
808.00       4
496.00       4
254.00       4
540.00       4
1560.00      4
175.00       4
208.00       4
318.00       4
590.00       4
846.00       4
399.00       4
288.00       4
896.00       4
466.00       4
220.00       4
522.00       4
516.00       4
197.00       4
742.00       4
297.00       4
282.00       4
503.00       4
1468.00      4
1530.00      4
402.00       4
400.00       4
588.00       4
736.00       4
560.00       4
720.00       4
901.00       4
849.00       4
938.00       4
611.00       4
552.00       4
75.00        4
616.00       4
462.00       4
864.00       4
72.00        4
135.00       4
554.00       4
201.00       4
520.00       4
363.00       4
697.00       4
925.00       4
268.00       4
725.00       4
815.00       4
1100.00      4
450.00       4
406.00       3
1017.00      3
415.00       3
234.00       3
411.00       3
225.00       3
341.00       3
486.00       3
142.00       3
1346.00      3
764.00       3
1129.00      3
801.00       3
431.00       3
732.00       3
831.00       3
918.00       3
702.00       3
223.00       3
320.00       3
179.00       3
678.00       3
470.00       3
510.00       3
161.00       3
403.00       3
661.00       3
357.00       3
247.00       3
144.00       3
656.00       3
89.00        3
105.00       3
153.00       3
189.00       3
1694.00      3
501.00       3
203.00       3
506.00       3
299.00       3
126.00       3
850.00       3
321.00       3
1258.00      3
193.00       3
967.00       3
370.00       3
595.00       3
98.00        3
343.00       3
184.00       3
1064.00      3
304.00       3
229.00       3
498.00       3
379.00       3
467.00       3
425.00       3
461.00       3
398.00       3
1330.00      3
868.00       3
55.00        3
219.00       3
371.00       3
78.00        3
222.00       3
811.00       3
1158.00      3
1114.00      3
122.00       3
612.00       3
932.00       3
167.00       3
121.00       3
265.00       3
1584.00      3
141.00       3
295.00       3
93.00        3
538.00       3
810.00       3
206.00       3
457.00       3
700.00       3
310.00       3
844.00       3
483.00       3
851.00       3
46.00        3
333.00       3
550.00       3
599.00       3
916.00       3
1496.00      3
1800.00      3
513.00       3
244.00       3
424.00       3
112.00       3
880.00       3
545.00       3
301.00       3
604.00       3
778.00       3
712.00       3
83.00        3
114.00       3
1632.00      3
213.00       3
25.00        3
430.00       3
191.00       3
413.00       3
1095.00      3
798.00       3
602.00       3
723.00       3
317.00       3
242.00       3
459.00       3
935.00       3
752.00       3
548.00       3
329.00       3
148.00       3
941.00       3
397.00       3
367.00       3
1140.00      3
325.00       3
207.00       3
427.00       3
372.00       3
99.00        3
1143.00      3
230.00       3
1528.00      3
171.00       3
666.00       3
569.00       3
939.00       3
102.00       3
238.00       3
285.00       3
279.00       3
48.00        3
133.00       3
137.00       2
722.00       2
994.00       2
763.00       2
789.00       2
663.00       2
1139.00      2
281.00       2
344.00       2
1588.00      2
1093.00      2
1232.00      2
134.00       2
1195.00      2
1595.00      2
1218.00      2
769.00       2
54.00        2
1055.00      2
650.00       2
892.00       2
290.00       2
610.00       2
586.00       2
534.00       2
500.00       2
412.00       2
136.00       2
1035.00      2
237.00       2
930.00       2
622.00       2
634.00       2
577.00       2
1128.00      2
198.00       2
70.00        2
1226.00      2
1198.00      2
311.00       2
1390.00      2
833.00       2
806.00       2
618.00       2
221.00       2
60.00        2
1026.00      2
395.00       2
158.00       2
1077.00      2
107.00       2
1181.00      2
1424.00      2
256.00       2
1362.00      2
567.00       2
1090.00      2
543.00       2
673.00       2
289.00       2
103.00       2
528.00       2
788.00       2
251.00       2
724.00       2
632.00       2
797.00       2
1082.00      2
1451.00      2
1405.00      2
1204.00      2
291.00       2
652.00       2
982.00       2
111.00       2
262.00       2
549.00       2
1043.00      2
1191.00      2
1436.00      2
364.00       2
1836.00      2
835.00       2
1450.00      2
626.00       2
345.00       2
182.00       2
266.00       2
165.00       2
429.00       2
1489.00      2
1152.00      2
664.00       2
1568.00      2
975.00       2
640.00       2
524.00       2
481.00       2
507.00       2
131.00       2
715.00       2
84.00        2
323.00       2
792.00       2
1054.00      2
1313.00      2
748.00       2
339.00       2
861.00       2
677.00       2
1240.00      2
972.00       2
740.00       2
927.00       2
1048.00      2
755.00       2
414.00       2
825.00       2
113.00       2
1276.00      2
104.00       2
605.00       2
479.00       2
508.00       2
704.00       2
649.00       2
117.00       2
1753.00      2
608.00       2
94.00        2
156.00       2
1092.00      2
526.00       2
338.00       2
64.00        2
332.00       2
1018.00      2
692.00       2
273.00       2
575.00       2
1656.00      2
1266.00      2
438.00       2
707.00       2
1580.00      2
1550.00      2
1498.00      2
794.00       2
1339.00      2
813.00       2
468.00       2
355.00       2
375.00       2
1375.00      2
177.00       2
196.00       2
487.00       2
77.00        2
437.00       2
352.00       2
330.00       2
1824.00      2
675.00       2
444.00       2
409.00       2
1117.00      2
680.00       2
876.00       2
739.00       2
1237.00      2
475.00       2
497.00       2
449.00       2
1046.00      2
718.00       2
1228.00      2
639.00       2
124.00       2
298.00       2
331.00       2
499.00       2
110.00       2
255.00       2
782.00       2
924.00       2
1257.00      2
1234.00      2
151.00       2
706.00       2
746.00       2
776.00       2
23.00        2
821.00       2
592.00       2
443.00       2
35.00        2
217.00       2
52.00        2
277.00       2
1074.00      2
762.00       2
1012.00      2
793.00       2
359.00       2
858.00       2
423.00       2
263.00       2
636.00       2
436.00       2
1342.00      2
783.00       2
1302.00      2
1316.00      2
56.00        2
953.00       2
969.00       2
770.00       2
1689.00      2
716.00       2
1335.00      2
1088.00      2
365.00       2
971.00       2
1594.00      2
1680.00      2
1065.00      2
658.00       2
374.00       2
765.00       2
169.00       2
750.00       2
637.00       2
366.00       2
530.00       2
717.00       2
187.00       2
635.00       2
95.00        2
1643.00      2
879.00       2
1290.00      2
495.00       2
215.00       2
860.00       2
1085.00      2
878.00       2
383.00       2
1491.00      2
781.00       2
644.00       2
494.00       2
945.00       2
369.00       2
1368.00      2
1288.00      2
848.00       2
1141.00      2
891.00       2
32.00        2
485.00       2
713.00       2
293.00       2
818.00       2
170.00       2
671.00       2
817.00       2
1020.00      2
872.00       2
1286.00      2
1045.00      1
233.00       1
589.00       1
327.00       1
709.00       1
836.00       1
1590.00      1
1544.00      1
1794.00      1
1515.00      1
1473.00      1
1296.00      1
1324.00      1
58.00        1
1393.00      1
1629.00      1
1217.00      1
488.00       1
659.00       1
1323.00      1
557.00       1
1604.00      1
1194.00      1
571.00       1
733.00       1
1116.00      1
827.00       1
777.00       1
164.00       1
888.00       1
1032.00      1
1768.00      1
74.00        1
1176.00      1
1250.00      1
86.00        1
296.00       1
458.00       1
1649.00      1
315.00       1
761.00       1
1121.00      1
974.00       1
804.00       1
657.00       1
877.00       1
1115.00      1
61.00        1
859.00       1
473.00       1
1958.00      1
1214.00      1
774.00       1
2002.00      1
1430.00      1
1344.00      1
1216.00      1
388.00       1
542.00       1
243.00       1
799.00       1
2046.00      1
1420.00      1
1058.00      1
471.00       1
1180.00      1
79.00        1
1926.00      1
1566.00      1
2042.00      1
1734.00      1
1736.00      1
1709.00      1
1603.00      1
1502.00      1
2336.00      1
1598.00      1
643.00       1
1084.00      1
745.00       1
1373.00      1
1357.00      1
1010.00      1
841.00       1
773.00       1
1264.00      1
1696.00      1
1614.00      1
1573.00      1
772.00       1
1402.00      1
645.00       1
1348.00      1
1087.00      1
1434.00      1
1332.00      1
721.00       1
28.00        1
1376.00      1
1726.00      1
183.00       1
249.00       1
1619.00      1
1442.00      1
563.00       1
50.00        1
613.00       1
314.00       1
1392.00      1
313.00       1
565.00       1
727.00       1
1866.00      1
1005.00      1
178.00       1
1248.00      1
996.00       1
559.00       1
1041.00      1
269.00       1
651.00       1
917.00       1
26.00        1
15.00        1
1022.00      1
679.00       1
1104.00      1
227.00       1
417.00       1
1622.00      1
382.00       1
1474.00      1
1097.00      1
866.00       1
871.00       1
1413.00      1
1072.00      1
335.00       1
1068.00      1
309.00       1
944.00       1
814.00       1
1212.00      1
1630.00      1
1480.00      1
155.00       1
615.00       1
464.00       1
1678.00      1
583.00       1
731.00       1
674.00       1
621.00       1
91.00        1
561.00       1
118.00       1
581.00       1
760.00       1
1013.00      1
1710.00      1
1527.00      1
387.00       1
578.00       1
898.00       1
1280.00      1
926.00       1
1122.00      1
547.00       1
1488.00      1
791.00       1
606.00       1
469.00       1
1444.00      1
14.00        1
275.00       1
442.00       1
908.00       1
454.00       1
1765.00      1
1486.00      1
1347.00      1
1318.00      1
1146.00      1
1173.00      1
1519.00      1
1242.00      1
1417.00      1
1341.00      1
1372.00      1
1428.00      1
1053.00      1
1660.00      1
361.00       1
1162.00      1
439.00       1
899.00       1
1328.00      1
1211.00      1
194.00       1
587.00       1
147.00       1
584.00       1
1304.00      1
1439.00      1
1625.00      1
1728.00      1
1497.00      1
619.00       1
305.00       1
1252.00      1
505.00       1
1319.00      1
529.00       1
580.00       1
998.00       1
539.00       1
453.00       1
181.00       1
828.00       1
931.00       1
407.00       1
620.00       1
1470.00      1
1050.00      1
869.00       1
949.00       1
862.00       1
992.00       1
NaN          1
1078.00      1
897.00       1
1272.00      1
647.00       1
451.00       1
852.00       1
907.00       1
1163.00      1
1615.00      1
631.00       1
154.00       1
1099.00      1
1777.00      1
257.00       1
334.00       1
726.00       1
1421.00      1
1508.00      1
1327.00      1
38.00        1
541.00       1
1307.00      1
823.00       1
758.00       1
940.00       1
389.00       1
591.00       1
568.00       1
555.00       1
910.00       1
574.00       1
1495.00      1
873.00       1
393.00       1
271.00       1
988.00       1
29.00        1
749.00       1
1168.00      1
903.00       1
1559.00      1
53.00        1
1028.00      1
22.00        1
214.00       1
1337.00      1
958.00       1
1774.00      1
730.00       1
2121.00      1
1108.00      1
1063.00      1
1935.00      1
2153.00      1
1626.00      1
1704.00      1
1582.00      1
1802.00      1
1706.00      1
1602.00      1
1298.00      1
272.00       1
729.00       1
1869.00      1
1300.00      1
1246.00      1
1510.00      1
1351.00      1
1066.00      1
989.00       1
1969.00      1
1369.00      1
1905.00      1
394.00       1
1795.00      1
1314.00      1
1120.00      1
874.00       1
1574.00      1
1685.00      1
1461.00      1
1349.00      1
39.00        1
1145.00      1
983.00       1
527.00       1
1081.00      1
1352.00      1
385.00       1
519.00       1
978.00       1
81.00        1
452.00       1
433.00       1
708.00       1
63.00        1
834.00       1
1144.00      1
928.00       1
551.00       1
735.00       1
882.00       1
691.00       1
246.00       1
1075.00      1
968.00       1
667.00       1
819.00       1
779.00       1
1221.00      1
809.00       1
966.00       1
999.00       1
771.00       1
977.00       1
948.00       1
20.00        1
231.00       1
109.00       1
951.00       1
1105.00      1
2140.00      1
1494.00      1
1482.00      1
349.00       1
1526.00      1
1453.00      1
1270.00      1
472.00       1
646.00       1
845.00       1
1284.00      1
1459.00      1
683.00       1
1422.00      1
1179.00      1
1125.00      1
123.00       1
1184.00      1
920.00       1
537.00       1
905.00       1
1262.00      1
961.00       1
957.00       1
106.00       1
856.00       1
17.00        1
963.00       1
1571.00      1
1638.00      1
82.00        1
593.00       1
1652.00      1
1094.00      1
914.00       1
27.00        1
185.00       1
149.00       1
1851.00      1
964.00       1
1670.00      1
893.00       1
1640.00      1
2062.00      1
889.00       1
1752.00      1
1410.00      1
523.00       1
995.00       1
42.00        1
127.00       1
1249.00      1
1618.00      1
690.00       1
1721.00      1
1030.00      1
1209.00      1
512.00       1
705.00       1
1251.00      1
1326.00      1
1052.00      1
767.00       1
1374.00      1
1273.00      1
1126.00      1
1406.00      1
655.00       1
358.00       1
1616.00      1
1504.00      1
1254.00      1
1293.00      1
1118.00      1
1400.00      1
1131.00      1
362.00       1
447.00       1
241.00       1
44.00        1
419.00       1
1203.00      1
435.00       1
1164.00      1
1098.00      1
34.00        1
1404.00      1
1380.00      1
307.00       1
303.00       1
1367.00      1
517.00       1
929.00       1
521.00       1
1153.00      1
418.00       1
1073.00      1
445.00       1
802.00       1
1556.00      1
465.00       1
236.00       1
863.00       1
502.00       1
648.00       1
906.00       1
1200.00      1
1107.00      1
1042.00      1
993.00       1
693.00       1
803.00       1
1007.00      1
477.00       1
1921.00      1
830.00       1
463.00       1
1967.00      1
1466.00      1
701.00       1
33.00        1
1411.00      1
1057.00      1
532.00       1
40.00        1
1308.00      1
515.00       1
260.00       1
1558.00      1
119.00       1
812.00       1
535.00       1
579.00       1
274.00       1
57.00        1
1541.00      1
428.00       1
668.00       1
258.00       1
1079.00      1
1150.00      1
976.00       1
795.00       1
128.00       1
734.00       1
1664.00      1
1907.00      1
1686.00      1
129.00       1
45.00        1
1503.00      1
239.00       1
Name: count, dtype: int64

----------------------------------------
BsmtFin SF 1:
 1 missing values
Percentage: 0.03%
BsmtFin SF 1
0.00       930
24.00       27
16.00       14
300.00       9
600.00       8
288.00       8
20.00        8
384.00       8
602.00       7
360.00       7
456.00       7
936.00       7
375.00       7
624.00       7
500.00       7
700.00       7
468.00       6
368.00       6
120.00       6
625.00       6
553.00       6
588.00       6
276.00       6
504.00       6
662.00       6
528.00       6
560.00       6
544.00       6
312.00       6
547.00       6
616.00       5
637.00       5
432.00       5
28.00        5
250.00       5
338.00       5
450.00       5
280.00       5
1200.00      5
697.00       5
648.00       5
686.00       5
104.00       5
353.00       5
672.00       5
915.00       5
400.00       5
904.00       5
595.00       5
144.00       5
196.00       5
732.00       5
784.00       5
767.00       5
330.00       5
252.00       5
550.00       5
336.00       5
758.00       5
168.00       5
734.00       4
1218.00      4
816.00       4
656.00       4
659.00       4
378.00       4
728.00       4
329.00       4
1059.00      4
247.00       4
1000.00      4
507.00       4
48.00        4
510.00       4
788.00       4
704.00       4
841.00       4
442.00       4
192.00       4
36.00        4
747.00       4
480.00       4
483.00       4
539.00       4
476.00       4
1036.00      4
828.00       4
986.00       4
56.00        4
836.00       4
988.00       4
425.00       4
781.00       4
812.00       4
410.00       4
660.00       4
864.00       4
549.00       4
403.00       4
612.00       4
490.00       4
428.00       4
390.00       4
546.00       4
633.00       4
495.00       4

In [15]:
df[varibles_with_missing_values].isnull().sum().sort_values(ascending=False)

Pool QC           2917
Misc Feature      2824
Alley             2732
Fence             2358
Mas Vnr Type      1775
Fireplace Qu      1422
Lot Frontage       490
Garage Cond        159
Garage Finish      159
Garage Qual        159
Garage Yr Blt      159
Garage Type        157
Bsmt Exposure       83
BsmtFin Type 2      81
Bsmt Cond           80
Bsmt Qual           80
BsmtFin Type 1      80
Mas Vnr Area        23
Bsmt Full Bath       2
Bsmt Half Bath       2
BsmtFin SF 1         1
Bsmt Unf SF          1
BsmtFin SF 2         1
Garage Cars          1
Garage Area          1
Electrical           1
Total Bsmt SF        1
dtype: int64

* Pool QC           2917 - Indica casas sem piscina (Structural Missing Data)
                         - Pool Area tem realação com essa variável, onde não há piscina área = 0 (imputar Nan?)

* Misc Feature      2824 - valor none proposital (Structural Missing Data)
                         - Misc Val tem relação com essa variável (imputar Nan?)

* Alley             2732 - NA significam casas sem acesso por beco (Structural Missing Data)

* Fence             2358 - casas sem cerca (Structural Missing Data)

* Mas Vnr Type      1775 - Não possuem revestimento, valor nulo proposital (Structural Missing Data)
                         - Porém, existem 7 linhas onde é nulo, mas possui área construída >0ft^2.
                         - Também existem 1745 valores que deveriam ser nulos com área = 0 - necessita imput de NaN  

* Fireplace Qu      1422 - Indica casas sem lareira (Structural Missing Data)

* Lot Frontage       490 - representa a distância linear da rua até a propriedade, provável falha no preenchimento da informação.
                         - Necessita uma estratégia de imput mais sofisticada
                         - Provável correlação com a irregularidade do terreno (?) (MAR?)

* Garage Cond        159 - Indica casas sem garagem (Structural Missing Data)
                         - Verificar justificativa da variável 'Garage Yr Blt'

* Garage Finish      159 - Indica casas sem garagem (Structural Missing Data)
                         - Verificar justificativa da variável 'Garage Yr Blt'

* Garage Qual        159 - Indica casas sem garagem (Structural Missing Data)
                         - Verificar justificativa da variável 'Garage Yr Blt'

* Garage Yr Blt      159 - Ano de contrução da garagem, como não há é nulo. (Structural Missing Data)
                         - Existem 2 linhas onde há garagem, mas não há ano de construção.
                            - uma das linhas possui área construída e vagas para carro (MCAR?)
                            - uma das linhas possui o tipo 'Detchd', mas não possui nenhuma outra informação.(MCAR?)
                            

* Garage Type        157 - Indica casas sem garagem (Structural Missing Data)
                         - Verificar justificativa da variável 'Garage Yr Blt'

* Bsmt Exposure       83 - Indica casas sem porão (Structural Missing Data)

* BsmtFin Type 2      81 - Indica casas sem porão (Structural Missing Data)

* Bsmt Cond           80 - Indica casas sem porão (Structural Missing Data)

* Bsmt Qual           80 - Indica casas sem porão (Structural Missing Data)

* BsmtFin Type 1      80 -  Indica casas sem porão (Structural Missing Data)

* Mas Vnr Area        23 - casas sem revestimento (Structural Missing Data)

* Bsmt Full Bath       2 - Essa variável indica quantidades de banheiros no porão, contudo, não existe porão nessas propriedades.
                           Isso explica o valor nulo. (Structural Missing Data)
                           - Em uma das linhas algumas características do porão está preenchida com 0, seria interessante inputar null.

* Bsmt Half Bath       2 - Mesma justificativa da variável acima 'Bsmt Full Bath'

* BsmtFin SF 1         1 - Não existe porão, justifica o valor nulo (Structural Missing Data)

* Bsmt Unf SF          1 - Mesma justificativa da variável acima 'BsmtFin SF 1'

* BsmtFin SF 2         1 - Mesma justificativa da variável acima 'BsmtFin SF 1'

* Garage Cars          1 - Corresponde a informação descrita em 'Garage Yr Blt'

* Garage Area          1 - Corresponde a informação descrita em 'Garage Yr Blt'

* Electrical           1 - Dado faltante sem explicação plausível. (MCAR?)

* Total Bsmt SF        1 - Corresponde a uma casa sem porão (Structural Missing Data)

In [16]:
# Verificando valores faltantes da coluna'pool qc' em relação a 'pool area'

df[df['Pool QC'].isnull()][['Pool Area', 'Pool QC']].value_counts(dropna=False)

Pool Area  Pool QC
0          NaN        2917
Name: count, dtype: int64

In [17]:
''' Verificando valores faltantes da coluna 'Mas Vnr Type' em relação a 'Mas Vnr Area'
 Observando que existem casos onde 'Mas Vnr Area' é maior ou igual a 0, mas 'Mas Vnr Type'
 está faltando, o que pode indicar uma inconsistência nos dados.'''

df.loc[(df['Mas Vnr Type'].isnull()) & (df['Mas Vnr Area'] >= 0), ['Mas Vnr Area', 'Mas Vnr Type']].value_counts(dropna=False)

Mas Vnr Area  Mas Vnr Type
0.00          NaN             1745
1.00          NaN                3
344.00        NaN                1
312.00        NaN                1
285.00        NaN                1
288.00        NaN                1
Name: count, dtype: int64

In [18]:
''' Verificando valores faltantes da coluna 'Misc Feature' em relação a 'Misc Val'
 Observando que existem casos onde 'Misc Val' é igual a 0, mas 'Misc Feature' está null,
 Pode indicar uma inconsistência nos dados.'''

df[df['Misc Feature'].isnull()][['Misc Feature', 'Misc Val']].value_counts(dropna=False)

Misc Feature  Misc Val
NaN           0           2824
Name: count, dtype: int64

In [ ]:
''' Verificando valores faltantes da coluna 'Fireplace Qu' em relação a 'Fireplaces'
Não há retorno de valores onde a quantidade de lareiras seja diferente de 0, o que indica que
Fireplace Qu está dentro do esperado (não existe lareira na propriedade)
'''

df[(df['Fireplace Qu'].isnull()) & (df['Fireplaces'] != 0)]

Empty DataFrame
Columns: [Order, PID, MS SubClass, MS Zoning, Lot Frontage, Lot Area, Street, Alley, Lot Shape, Land Contour, Utilities, Lot Config, Land Slope, Neighborhood, Condition 1, Condition 2, Bldg Type, House Style, Overall Qual, Overall Cond, Year Built, Year Remod/Add, Roof Style, Roof Matl, Exterior 1st, Exterior 2nd, Mas Vnr Type, Mas Vnr Area, Exter Qual, Exter Cond, Foundation, Bsmt Qual, Bsmt Cond, Bsmt Exposure, BsmtFin Type 1, BsmtFin SF 1, BsmtFin Type 2, BsmtFin SF 2, Bsmt Unf SF, Total Bsmt SF, Heating, Heating QC, Central Air, Electrical, 1st Flr SF, 2nd Flr SF, Low Qual Fin SF, Gr Liv Area, Bsmt Full Bath, Bsmt Half Bath, Full Bath, Half Bath, Bedroom AbvGr, Kitchen AbvGr, Kitchen Qual, TotRms AbvGrd, Functional, Fireplaces, Fireplace Qu, Garage Type, Garage Yr Blt, Garage Finish, Garage Cars, Garage Area, Garage Qual, Garage Cond, Paved Drive, Wood Deck SF, Open Porch SF, Enclosed Porch, 3Ssn Porch, Screen Porch, Pool Area, Pool QC, Fence, Misc Feature, Misc Val, Mo Sold, Yr Sold, Sale Type, Sale Condition, SalePrice]
Index: []

In [21]:
''' Verificando valores faltantes da coluna 'Lot Frontage' em relação a 'Lot Shape'
 Observando a possibilidade de que os valores faltantes ou negativos em 'Lot Frontage'
possam estar relacionados a diferentes formas de lote, o que pode indicar uma inconsistência nos dados.'''

df.loc[(df['Lot Frontage'].isnull()) | (df['Lot Frontage'] <= 0), ['Lot Frontage', 'Lot Shape']].groupby('Lot Shape').size().sort_values(ascending=False)

Lot Shape
IR1    325
Reg    132
IR2     28
IR3      5
dtype: int64

In [22]:
''' Verificando por que os valores faltantes da coluna 'Garage Type' não estão de acordo com 'Garage Yr Blt'
'''

df.loc[(df['Garage Yr Blt'].isnull()), ['Garage Type', 'Garage Yr Blt', ]].value_counts(dropna=False)

Garage Type  Garage Yr Blt
NaN          NaN              157
Detchd       NaN                2
Name: count, dtype: int64

In [23]:
''' No índice 1356, 'Garage Type' é 'Detchd', possui quantidade de carros suportados e área de garagem.
Provavelmente essa garagem existe, mas houve falha na coleta das outras informações, como o ano de construção,
acababento, qualidade e condição

Já no índice 2236, 'Garage Type' é 'Detchd', mas não possui quantidade de carros suportados e área de garagem,
o que pode indicar que a garagem não existe ou que houve erro no preenchimento da informação.'''

df.loc[(df['Garage Type'] == 'Detchd') & (df['Garage Yr Blt'].isnull())]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1356,1357,903426160,60,RM,57.00,8094,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2.5Unf,6,8,1910,1983,Gable,CompShg,Wd Sdng,Wd Sdng,NaN,0.00,TA,TA,PConc,TA,TA,Mn,Rec,196.00,Unf,0.00,1046.00,1242.00,GasA,Gd,Y,SBrkr,1242,742,0,1984,0.00,0.00,2,0,5,1,TA,8,Typ,0,NaN,Detchd,NaN,NaN,1.00,360.00,NaN,NaN,Y,64,0,180,0,0,0,NaN,MnPrv,Shed,1000,9,2008,WD,Normal,160000
2236,2237,910201180,70,RM,50.00,9060,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,2Story,5,6,1923,1999,Gable,CompShg,Wd Sdng,Plywood,NaN,0.00,TA,TA,BrkTil,Gd,TA,No,ALQ,548.00,Unf,0.00,311.00,859.00,GasA,Ex,Y,SBrkr,942,886,0,1828,0.00,0.00,2,0,3,1,Gd,6,Typ,0,NaN,Detchd,NaN,NaN,NaN,NaN,NaN,NaN,Y,174,0,212,0,0,0,NaN,MnPrv,NaN,0,3,2007,WD,Alloca,150909

In [24]:
''' Investigando variaveis 'Bsmt' 
'''

df.loc[:, df.columns.str.startswith('Bsmt')].isnull().sum()

Bsmt Qual         80
Bsmt Cond         80
Bsmt Exposure     83
BsmtFin Type 1    80
BsmtFin SF 1       1
BsmtFin Type 2    81
BsmtFin SF 2       1
Bsmt Unf SF        1
Bsmt Full Bath     2
Bsmt Half Bath     2
dtype: int64

In [25]:


df[df['Total Bsmt SF'].isnull()]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1341,1342,903230120,20,RM,99.00,5940,Pave,NaN,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,NaN,0.00,TA,TA,PConc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,NaN,Detchd,1946.00,Unf,1.00,280.00,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,4,2008,ConLD,Abnorml,79000

In [26]:
'''
Linha 444 possui 'BsmtFin SF 2' , ou seja, existe uma segunda área com acabamento do porão, mas 'BsmtFin Type 2'
está null, não há qual tipo de acabamento e está preenchido como se não houvesse porão. 
'''
df[(df['BsmtFin SF 2'] != 0) & (df['BsmtFin Type 2'].isnull())]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
444,445,528142130,20,RL,85.00,10655,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,8,5,2003,2004,Gable,CompShg,VinylSd,VinylSd,BrkFace,296.00,Gd,TA,PConc,Gd,TA,No,GLQ,1124.00,NaN,479.00,1603.00,3206.00,GasA,Ex,Y,SBrkr,1629,0,0,1629,1.00,0.00,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2003.00,RFn,3.00,880.00,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,10,2009,WD,Normal,284000
1341,1342,903230120,20,RM,99.00,5940,Pave,NaN,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,NaN,0.00,TA,TA,PConc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,NaN,Detchd,1946.00,Unf,1.00,280.00,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,4,2008,ConLD,Abnorml,79000

In [27]:
'''
Não há porão nesas linhas, isso explica os dados nulos em quantidade de banheiros no porão.
'''
df[df['Bsmt Full Bath'].isnull()]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1341,1342,903230120,20,RM,99.00,5940,Pave,NaN,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,NaN,0.00,TA,TA,PConc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,NaN,Detchd,1946.00,Unf,1.00,280.00,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,4,2008,ConLD,Abnorml,79000
1497,1498,908154080,20,RL,123.00,47007,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,7,1959,1996,Gable,CompShg,Plywood,Plywood,NaN,0.00,TA,TA,Slab,NaN,NaN,NaN,NaN,0.00,NaN,0.00,0.00,0.00,GasA,TA,Y,SBrkr,3820,0,0,3820,NaN,NaN,3,1,5,1,Ex,11,Typ,2,Gd,Attchd,1959.00,Unf,2.00,624.00,TA,TA,Y,0,372,0,0,0,0,NaN,NaN,NaN,0,7,2008,WD,Normal,284700

In [28]:
df[(df['BsmtFin SF 1'].isnull()) | (df['Bsmt Unf SF'].isnull()) | (df['BsmtFin SF 2'].isnull())]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1341,1342,903230120,20,RM,99.00,5940,Pave,NaN,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,NaN,0.00,TA,TA,PConc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,NaN,Detchd,1946.00,Unf,1.00,280.00,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,4,2008,ConLD,Abnorml,79000

In [29]:
df[df['Bsmt Exposure'].isnull() & (df['BsmtFin SF 1'].isnull())]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1341,1342,903230120,20,RM,99.00,5940,Pave,NaN,IR1,Lvl,AllPub,FR3,Gtl,BrkSide,Feedr,Norm,1Fam,1Story,4,7,1946,1950,Gable,CompShg,MetalSd,CBlock,NaN,0.00,TA,TA,PConc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GasA,TA,Y,FuseA,896,0,0,896,NaN,NaN,1,0,2,1,TA,4,Typ,0,NaN,Detchd,1946.00,Unf,1.00,280.00,TA,TA,Y,0,0,0,0,0,0,NaN,MnPrv,NaN,0,4,2008,ConLD,Abnorml,79000

In [31]:
df[df['Electrical'].isnull()]

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
1577,1578,916386080,80,RL,73.00,9735,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Timber,Norm,Norm,1Fam,SLvl,5,5,2006,2007,Gable,CompShg,VinylSd,VinylSd,NaN,0.00,TA,TA,PConc,Gd,TA,No,Unf,0.00,Unf,0.00,384.00,384.00,GasA,Gd,Y,NaN,754,640,0,1394,0.00,0.00,2,1,3,1,Gd,7,Typ,0,NaN,BuiltIn,2007.00,Fin,2.00,400.00,TA,TA,Y,100,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500